# Generated by Django 4.2.7 on 2023-11-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reservarhora'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservarhora',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
